version: 2
jobs:
  build-and-unit-test:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/ts-electron
    steps:
      - checkout
      - run:
          name: update-npm
          command: sudo npm install -g npm@latest
      - run:
          name: npm-install
          command: npm ci
      - run:
          name: build-sqlite3
          command: cd app && npm install sqlite3 --build-from-source
      - run:
          name: build
          command: npm run build
      - run:
          name: unit-test
          command: MOCHA_FILE="junit/unit-test-results.xml" npm run test:unit:ci
      - store_test_results:
          path: ~/ts-electron/junit
      - store_artifacts:
          path: ~/ts-electron/junit
  package-and-integration-test:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/ts-electron
    steps:
      - checkout
      - run:
          name: update-npm
          command: sudo npm install -g npm@latest
      - run:
          name: npm-install
          command: npm ci
      - run:
          name: install-required-packages
          command: sudo apt -y install icnsutils graphicsmagick
      - run:
          name: package
          command: npm run package
      - run:
          name: integration-test
          command: MOCHA_FILE="junit/integration-test-results.xml" npm run test:integration:ci
      - store_test_results:
          path: ~/ts-electron/junit
      - store_artifacts:
          path: ~/ts-electron/junit
      - store_artifacts:
          path: ~/ts-electron/dist

workflows:
  version: 2
  workflow:
    jobs:
      - build-and-unit-test
      - package-and-integration-test:
          requires:
            - build-and-unit-test
          filters:
            branches:
              only: master